apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wgoswshr1-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:f1be2a5d8f9dfeec26ad03e92184c0fb92406c77@sha256:3ba554aa9b514ea5bd678ac4f3614d3527f8add8655936aa3ceadb2f062ce08f
          name: container-image
